libcontainer: Include limits.h, needed for PATH_MAX
This was failing to build with:

[1/2] CC obj/libcontainer/libcontainer.libcontainer.o
FAILED: obj/libcontainer/libcontainer.libcontainer.o
armv7a-cros-linux-gnueabi-clang -MMD -MF obj/libcontainer/libcontainer.libcontainer.o.d -DUSE_device_mapper=0 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I../../../../..
/../../../../mnt/host/source/src/platform2/libcontainer -Iobj/libcontainer/libcontainer.gen/include -Igen/include -I/mnt/host/source/src/platform2 -I/mnt/host/source/src/platform -I/build/loo
nix/usr/include -Wall -Wno-psabi -Wunused -Wno-unused-parameter -ggdb3 -fstack-protector-strong -Wformat=2 -fvisibility=internal -Wa,--noexecstack -Werror --sysroot=/build/loonix -fvisibility
=default -I/build/loonix/usr/include/chromeos -fPIC -std=gnu11 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -O2 -O2 -pipe -march=armv7-a -mtune=cortex-a9 -mfpu=neon -mfloa
t-abi=hard -g -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -clang-syntax -clang-syntax -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables  -c ../../../..
/../../../../../mnt/host/source/src/platform2/libcontainer/libcontainer.c -o obj/libcontainer/libcontainer.libcontainer.o
../../../../../../../../../mnt/host/source/src/platform2/libcontainer/libcontainer.c:1449:17: error: use of undeclared identifier 'PATH_MAX'
        char exec_path[PATH_MAX];

BUG=b:64269804
TEST=`ebuild-loonix libcontainer-9999.ebuild compile` succeeds.

Change-Id: I13f7e446550701d5191f2c4bb0737fc19d4e1c31
Reviewed-on: https://chromium-review.googlesource.com/660992
Commit-Ready: Joshua Emele <jemele@google.com>
Tested-by: Joshua Emele <jemele@google.com>
Reviewed-by: Dylan Reid <dgreid@chromium.org>