xidle: fix signed build warnings
Building with base headers in a SLOT-ed setup exposes a minor build
warning (which causes failures due to -Werror):

In file included from xidle.cc:10:0:
.../base/logging.h: In function 'std::string* logging::CheckNEImpl(const t1&, const t2&, const char*)
                                 [with t1 = long unsigned int, t2 = int, std::string = std::basic_string<char>]':
xidle.cc:69:3:   instantiated from here
.../base/logging.h:513:1: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]

Explicitly cast the 0 constant to avoid this.

BUG=chromium-os:16623
TEST=`emerge-x86-alex power_manager` builds

Change-Id: Ib5bcf5eab910461297104b4963e6c0e14b29c340
Reviewed-on: https://gerrit.chromium.org/gerrit/15957
Reviewed-by: Daniel Erat <derat@chromium.org>
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>