authpolicy: Fix constexpr usage to be able to build with libc++.
std::make_pair requires minimum std=c++14 to be able to return constexpr
and libc++ enforces this restriction.
As platform libs are targeted to use gnu++11 std, change constexpr to const
at a few places to avoid compilation errors when using libc++.

src/platform2/authpolicy/samba_interface.cc:67:32: error: constexpr variable
'kDirsAndMode' must be initialized by a constant expression
constexpr std::pair<Path, int> kDirsAndMode[] = {
                               ^                ~
../../../../../../../../../mnt/host/source/src/platform2/authpolicy/samba_interface.cc:68:5: note: non-constexpr constructor
'pair<authpolicy::Path, const int &, false>' cannot be used in a constant expression
    {Path::TEMP_DIR, kFileMode_rwxrx},
    ^
../../../../../../../usr/include/c++/v1/utility:436:5: note: declared here
    pair(_U1&& __u1, _U2&& __u2)
    ^

src/platform2/authpolicy/policy/device_policy_encoder.cc:23:39: error: constexpr variable
'kConnectionTypes' must be initialized by a constant expression
constexpr std::pair<const char*, int> kConnectionTypes[] = {
                                      ^                    ~
src/platform2/authpolicy/policy/device_policy_encoder.cc:24:5: note: non-constexpr
constructor 'pair<const char *, enterprise_management::AutoUpdateSettingsProto_ConnectionType, false>' cannot be used in a constant
expression
    std::make_pair(
    ^
../../../../../../../usr/include/c++/v1/utility:464:5: note: declared here
    pair(pair<_U1, _U2>&& __p)
    ^

BUG=chromium:724628
TEST=authpolicy compiles with libc++.

Change-Id: I64cfac3d8942173e89b0fe5dd5d25b1fc5bf669d
Reviewed-on: https://chromium-review.googlesource.com/578449
Commit-Ready: Manoj Gupta <manojgupta@chromium.org>
Tested-by: Manoj Gupta <manojgupta@chromium.org>
Reviewed-by: Lutz Justen <ljusten@chromium.org>