Revert "common-mk: Kill any auxiliary child processes after the child terminates."
This introduced failures in amd-x86-generic-asan with the message

  Error: the test leaked process llvm-symbolizer with pid 87 (it was forcefully killed)

The issue appears to have occurred while running the tests for package cryptohome-0.0.1-r1183.

This reverts commit 90ed00fd305236a1acbbf2e8189f257228189530.

Change-Id: I13000b496478b9d7eac52e1148be7ce9f987a784
Reviewed-on: https://chromium-review.googlesource.com/340541
Commit-Ready: Jacob Dufault <jdufault@chromium.org>
Tested-by: Jacob Dufault <jdufault@chromium.org>
Reviewed-by: Dylan Reid <dgreid@chromium.org>