biod: Fix out of order struct initialization.
Fix the warning introduced by latest clang:
ec_command.h:59:21: error: ISO C++ requires field designators to be
specified in declaration order; field 'result' will be initialized
after field 'insize' [-Werror,-Wreorder-init-list]

BUG=chromium:1001317
TEST=biod builds for amd64-generic.

Change-Id: I98a6d4046919158b485ff6987f4669cbef4f8017
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/1896182
Reviewed-by: Nicolas Norvez <norvez@chromium.org>
Reviewed-by: Caroline Tice <cmtice@chromium.org>
Commit-Queue: Manoj Gupta <manojgupta@chromium.org>
Tested-by: Manoj Gupta <manojgupta@chromium.org>