common-mk: Suppress -Wrange-loop-analysis warning
Disable range-loop-analysis warning in platform2 to unblock llvm-next
builds failing with the following warning in libbrillo which can't be
easily fixed:

data_serialization.h:471:20: error: loop variable 'element' is always a
copy because the range of type 'const std::vector<bool, allocator<bool>
>' does not return a reference [-Werror,-Wrange-loop-analysis]
  for (const auto& element : value) {
                                ^
use non-reference type
'std::__1::__bit_const_reference<std::__1::vector<bool,
std::__1::allocator<bool> > >'

BUG=chromium:1042979
TEST=emerge-kevin libbrillo

Change-Id: If5b70cb1a836df325d3683217be4c841fc7a5516
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/2008102
Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
Reviewed-by: Chris McDonald <cjmcdonald@chromium.org>
Tested-by: Manoj Gupta <manojgupta@chromium.org>