intel: ipu3: Fix cts testJpegExif fail
[Issue]
1. focal length expected:<0.0> but was:<2.97>

[Root Cause]
1. hal not update platform focal length metadata to default request

[Changes]
1. get platform metadata ANDROID_LENS_INFO_AVAILABLE_FOCAL_LENGTHS
2. update value to request metadata ANDROID_LENS_FOCAL_LENGTH

BUG=b:111770990
TEST=Build and deploy package to platform and camera works

Change-Id: I63f8c3bfe84a75f29ca01b3f02ea2933311bab43
Signed-off-by: yushua1x <shuangx.yu@intel.com>
Reviewed-on: https://chromium-review.googlesource.com/1180844
Commit-Ready: Wei Meng <wei.meng@intel.corp-partner.google.com>
Tested-by: Wei Meng <wei.meng@intel.corp-partner.google.com>
Reviewed-by: Ricky Liang <jcliang@chromium.org>