cromo: Silence -Wunreachable-code warnings
clang's -Wunreachable-code doesn't like this:

.../platform2/cromo/sms_message.cc:356:17: error: code will never be executed [-Werror,-Wunreachable-code]
    std::string hexpdu;
                ^~~~~~
.../platform2/cromo/sms_message.cc:355:7: note: silence by adding parentheses to mark code as explicitly dead
  if (false) {  // Change to true for debug logging of PDU data
      ^
      /* DISABLES CODE */ ( )

This is debug code, so just employ the silencing that clang suggests.

BUG=none
TEST=precq; build with CL:1330972

Change-Id: Ifc8eb8091f746cf531306d63c12a3efd2650a374
Signed-off-by: Brian Norris <briannorris@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1334489
Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
Reviewed-by: Ben Chan <benchan@chromium.org>