intel: ipu3: unroll single-run loop
clang's -Wunreachable-code doesn't like this loop, since the iteration
statement will never be called.

  cros-camera-hal-intel-ipu3-0.0.1-r152: .../platform/arc-camera/hal/intel/psl/ipu3/GraphConfigManager.cpp:708:9: error: loop will run at most once (loop increment never executed) [-Werror,-Wunreachable-code-loop-increment]
  cros-camera-hal-intel-ipu3-0.0.1-r152:         for (auto& it : mGraphConfigMap) {
  cros-camera-hal-intel-ipu3-0.0.1-r152:         ^~~

We can unroll it instead.

BUG=none
TEST=precq; build with and without CL:1330972

Change-Id: I30ea7ed2c14a124b51fb09cb69fb6027e54a99ee
Signed-off-by: Brian Norris <briannorris@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1351840