chromeos-install: Detect x86_64 as intel arch
chromeos-install gives an error:

Error: Failed to auto detect architecture

Looks like the crosh throws this error too, since chromeos-install is
invoked when it's started.

Change-Id: Icb695605bc2fdef515dff10cc0d64bef0d7c04b6

Review URL: http://codereview.chromium.org/3143034