camera: mediatek: Fix compiler error
The new compiler throws an error during cros-camera-hal-mtk build:

"P2_Processor.h:83:31: error: no matching constructor for initialization
of 'std::lock_guard<std::mutex>',
candidate constructor not viable: 1st argument ('const std::mutex')
would lose const qualifier"

Fix the error by removing constant qualifier from isEnable() since the
method modifies the internal member mThreadMutex.

BUG=chromium:1047221
TEST=`emerge-kukui cros-camera-hal-mtk` passes with llvm-next.

Change-Id: I606b9c522fd89fb9fdb290887629233a47736176
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/2037465
Reviewed-by: Hung-yu Wu <hywu@chromium.org>
Commit-Queue: Denis Nikitin <denik@chromium.org>
Tested-by: Denis Nikitin <denik@chromium.org>