Revert "common-mk: update platform2.py to support both portage versions"
This reverts commit a9c421be970a4a2187124665ec75b24ac8e53fc7.

This is breaking the sdk bot for some reason:

 /var/tmp/portage/chromeos-base/libchromeos-0.0.1-r167/work/libchromeos-0.0.1/platform2/common-mk/platform2.py --host --libdir=/usr/lib64 --use_flags=amd64 cros_host elibc_glibc kernel_linux multilib userland_GNU --action=configure --cache_dir=/var/cache/portage/chromeos-base/libchromeos /var/tmp/portage/chromeos-base/libchromeos-0.0.1-r167/work/libchromeos-0.0.1/platform2/libchromeos/libchromeos.gyp
 Traceback (most recent call last):
   File "/var/tmp/portage/chromeos-base/libchromeos-0.0.1-r167/work/libchromeos-0.0.1/platform2/common-mk/platform2.py", line 18, in <module>
     from chromite.lib.cros_build_lib import ShellUnquote
 ImportError: No module named chromite.lib.cros_build_lib

Change-Id: Ia436e9561a6270315c242a7d4e83ab7a72cfdbbb
Reviewed-on: https://chromium-review.googlesource.com/213000
Reviewed-by: Bertrand Simonnet <bsimonnet@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>