usb_v1: Remove single-run loop
Enabling -Wunreachable-code, clang doesn't like this loop, which is
really only supposed to run once:

arc-camera-service-0.0.1-r165: .../arc-camera/hal/usb_v1/v4l2_camera_device.cc:633:3: error: loop will run at most once (loop increment never executed) [-Werror,-Wunreachable-code-loop-increment]
arc-camera-service-0.0.1-r165:   for (const auto& device : video_devices) {
arc-camera-service-0.0.1-r165:   ^~~

Let's unroll it, to make it clearer and silence the warning

BUG=none
TEST=precq; build with CL:1330972

Change-Id: Ic0bb5e38d41637002d997ef5251fa7fc2066db76
Signed-off-by: Brian Norris <briannorris@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1332811
Reviewed-by: Shik Chen <shik@chromium.org>