vm_tools: sommelier: handle unreachable exit()
With -Wunreachable-code (CL:1330972), clang doesn't like this:

  vm_guest_tools-0.0.1-r220: .../platform2/vm_tools/sommelier/sommelier.c:3516:5: error: code will never be executed [-Werror,-Wunreachable-code]
  vm_guest_tools-0.0.1-r220:     _exit(EXIT_FAILURE);
  vm_guest_tools-0.0.1-r220:     ^~~~~

Just make this an assert() instead, because it is truly dead, and we
really only want to guard against future control flow changes that might
break that assumption.

BUG=none
TEST=precq; build with CL:1330972

Change-Id: Ic5decccb8a4787cdfd09824281d6f0254b87f868
Signed-off-by: Brian Norris <briannorris@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1351683
Reviewed-by: Stephen Barber <smbarber@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>