cryptohome: Fixed unused local variable warning.
cryptohome-0.0.1-r2177:
../../../../../../../tmp/portage/chromeos-base/cryptohome-0.0.1-r2177/work/cryptohome-0.0.1/platform2/cryptohome/mount.cc:1624:35:
error: unused variable 'ent_iter' [-Werror,-Wunused-variable]
cryptohome-0.0.1-r2177:   std::vector<FilePath>::iterator ent_iter;

BUG=chromium:778316
TEST=verified warning is gone

Change-Id: I4e18e8f51c6d1ab481682a6390082207a5960a84
Reviewed-on: https://chromium-review.googlesource.com/738157
Commit-Ready: Luis Lozano <llozano@chromium.org>
Tested-by: Luis Lozano <llozano@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>