fix unused variable error
The previous clean up left behind kSocketError which breaks in unittests:
shill/connection_health_checker_unittest.cc:62:11: error: unused variable 'kSocketError' [-Werror,-Wunused-const-variable]

BUG=chromium:385182
TEST=None

Change-Id: I0b6bd48cff80c6f9b3237ea680a85db9d8a44713
Reviewed-on: https://chromium-review.googlesource.com/205360
Reviewed-by: mukesh agrawal <quiche@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>