hammerd: Fix switch case fallthrough warning
Fix fall-through between switch labels detected
by clang warning -Wimplicit-fallthrough.
No changes in code flow.

CL fixes the following warning:
hammer_updater.cc:499:5: error: unannotated fall-through between switch
labels [-Werror,-Wimplicit-fallthrough]

BUG=chromium:904913
TEST=package build with -Wimplicit-fallthrough is fixed

Change-Id: I882632e9d9c36e15e5dbba9217738c9691fd4bc4
Reviewed-on: https://chromium-review.googlesource.com/1676594
Tested-by: Denis Nikitin <denik@chromium.org>
Commit-Ready: Denis Nikitin <denik@chromium.org>
Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
Reviewed-by: Joel Kitching <kitching@chromium.org>
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>
Reviewed-by: Manoj Gupta <manojgupta@chromium.org>