depend on gthread/gobject
The cros-disks main code refers to funcs from both gthread and gobject,
so make sure we link them in rather than relying on other libraries.

Otherwise, we get link failures like so:
LDCXX		disks
ld.gold: main.pie.o: in function main:.../main.cc:70: error: undefined reference to 'g_type_init'
ld.gold: main.pie.o: in function main:.../main.cc:71: error: undefined reference to 'g_thread_init'
collect2: ld returned 1 exit status
make[1]: *** [CXX_BINARY(disks)] Error 1

BUG=chromium-os:26736
TEST=`emerge-x86-alex cros-disks` still works

Change-Id: I617858e9099827cda17160052a0191b0becb81b7
Reviewed-on: https://gerrit.chromium.org/gerrit/17471
Reviewed-by: Brian Harring <ferringb@chromium.org>
Reviewed-by: Kees Cook <keescook@chromium.org>
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>