hammerd: fix the error when running hammerd_api_demo.py
When running the hammerd_api_demo.py in the DUT, the below error
popped out. To fix it, we need to add the public key to avoid the error.
Traceback (most recent call last):
  File "/usr/bin/hammerd_api_demo.py", line 51, in <module>
    main()
  File "/usr/bin/hammerd_api_demo.py", line 35, in main
    challenge_status = pair_manager.PairChallenge(updater.object)
  File "/usr/local/lib/python-exec/python2.7/hammerd_api.py", line 125, in method
    (method_name, len(argtypes) - 1, len(args)))
TypeError: PairChallenge expected 2 arguments, got 1.

We also fix the lint warning below by adding coding utf-8:
R:  1, 0: File encoding missing (the first line after the shebang should be "# -*- coding: utf-8 -*-") (missing-file-encoding)

BUG=b:142042503
TEST=successfully ran hammerd_api.py

Change-Id: I244428387100b00510d65e3e92e317f5188bc48c
Reviewed-on: https://chromium-review.googlesource.com/1846692
Tested-by: Zhuohao Lee <zhuohao@chromium.org>
Commit-Ready: Zhuohao Lee <zhuohao@chromium.org>
Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>