Fix power_manager for gcc 4.7 build.
This fix adds "virtual" to power_manager::AmbientLightSensor destructor, the error was -

    power_manager-0.0.1-r545:
    ../../../../../../../usr/include/base-125070/base/memory/scoped_ptr.h:137:5:
    error: deleting object of polymorphic class type
    'power_manager::AmbientLightSensor' which has non-virtual
    destructor might cause undefined behaviour
    [-Werror=delete-non-virtual-dtor]

BUG=None
TEST=built using gcc 4.7

Change-Id: I5ff078aee9fbca2547ab61556adc078ed82d4f13
Reviewed-on: https://gerrit.chromium.org/gerrit/34092
Reviewed-by: Daniel Erat <derat@chromium.org>
Commit-Ready: Han Shen <shenhan@chromium.org>
Tested-by: Han Shen <shenhan@chromium.org>